### ISSUE TITLE
Fails to install with about import error

### ISSUE THREAD

**Issue by wichert** [boisgera/pandoc#1]
pandoc is not installable currently:

```
Downloading/unpacking pandoc
  Downloading pandoc-1.0.0-alpha.tar.gz
  Running setup.py egg_info for package pandoc
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/Users/wichert/proj/build/pandoc/setup.py", line 10, in <module>
        import about
    ImportError: No module named about
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/Users/wichert/proj/build/pandoc/setup.py", line 10, in <module>

    import about

ImportError: No module named about
```

**Comment by boisgera** [comment]
@pconerly

I second this ; if you need to invoke pandoc right now from Python, please use pypandoc or os.system, etc. (I personnaly use [sh](https://github.com/amoffat/sh)). 

This project is not ready for prime time ; its main aim is also not to be thin wrapper on top of pandoc (the Haskell prg), but to provide a Pythonic model for pandoc documents to enable users to inspect, query, transform, etc. these objects with familiar methods.

**Comment by boisgera** [comment]
@pconerly 

You should be able to install this module now.
