### ISSUE TITLE
Support latest version of Pandoc

### ISSUE THREAD

**Issue by boisgera** [boisgera/pandoc#25]
Pandoc 2.12 and 2.13  are out ; the former is avaible for all platforms for conda (2.13 not packaged yet).

Update: 2.14.1 is out (July 2011).

  - [x] Support pandoc ~~2.12~~ 2.14.1,
  - [x] Update the conda dev environment,
  - [x] Update the documentation (pick ~~2.12~~ 2.14.1 as a new reference).

**Comment by rddaz2013** [comment]
Yes, please.....ValueError: pandoc 2.12 is not registered

**Comment by boisgera** [comment]
Pandoc 2.14.1 has been released (2021-07-18), I have used this version as a new reference (see beee5ad6850903b25d54b8bf9525130c161c5240).
