### ISSUE TITLE
mkdocs: pages to nav

### ISSUE THREAD

**Issue by boisgera** [boisgera/pandoc#28]
Deal with the warning:

    WARNING  -  Config value: 'pages'. Warning: The 'pages' configuration option has been deprecated and will be removed in a future release of
                MkDocs. Use 'nav' instead.

**Comment by denglianwei** [comment]
Solved?

**Comment by boisgera** [comment]
Yep ; 77ab891a62275e72d9ae6265950b52c35a9c6a62 did the trick AFAICT.

**Comment by denglianwei** [comment]
thank you
