### ISSUE TITLE
Hard-coded to use pandoc 1.12?

### ISSUE THREAD

**Issue by msabramo** [boisgera/pandoc#3]
```
In [1]: import pandoc
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-6bf4f957f9b9> in <module>()
----> 1 import pandoc

/Users/marca/dev/git-repos/pandoc/pandoc.py in <module>()
     23     assert version.startswith("1.12")
     24 except:
---> 25     raise ImportError("cannot find pandoc 1.12")
     26
     27 # TODO: rethink the tuple thing. Tuple may yield a structure closer to the

ImportError: cannot find pandoc 1.12
```

**Comment by boisgera** [comment]
Relaxed the constraint to pandoc 1.12 or 1.13. 

Pandoc (the python module) needs the json representation of pandoc (the Haskell program) to be stable. Raising an error when the version doesn't match the set that should work is a way to avoid later errors. That may be a bit extreme ...

**Comment by msabramo** [comment]
Could make it a warning perhaps?

One way to guarantee a compatible pandoc is to package the the whole thing up as a Docker container.

**Comment by boisgera** [comment]
The current version of the library doesn't require pandoc (the command-line tool) to be installed.
