### ISSUE TITLE
v2.3b0 -> 2.4b0?

### ISSUE THREAD

**Issue by jayvdb** [boisgera/pandoc#56]
https://github.com/boisgera/pandoc/releases/tag/v2.3b0 was tagged last week, while v2.3 was Nov 2022.  Should this recent tag have been 2.4b0 ?

**Comment by boisgera** [comment]
Absolutely! Thanks for the report and sorry for the mistake.

**Comment by boisgera** [comment]
Release with the correct version tag: https://github.com/boisgera/pandoc/releases/tag/v2.4b0
