### ISSUE TITLE
Are the binaries included? [Question]

### ISSUE THREAD

**Issue by HeIIow2** [boisgera/pandoc#57]
Hi,

My usecase for pandoc is just to convert between `markdown`, `html` and `asciidoc` in all direction. Pandoc works great for that *(though maybe a bit overkill but hey, it does the job)*. But another requirement is for it to be easily installed via pip.

Now my question is, if the pandoc binaries are already included, if it needs pandoc installed on the system, or even if it is a reimplementation of pandoc. 

If it has to be seperately installed, do you maybe know any alternative for my above described uscase? Ik this might not be the most appropriate place to ask this, but I really couldn't find anything. So sorry!

Anyways, thanks for your time and this project,
have a nice day :3

**Comment by boisgera** [comment]
Hi,

No, the pandoc binary is not included in the `pandoc` Pypi package (this project).

I'd LOVE to be able to do that but AFAICT noone managed to pull that off (not pypandoc, not panflute, etc.).
Technically, the pandoc binary comes from a Haskell codebase and I've never heard of any such project being integrated with Pypi.

The simplest way to install this binary in the Python world is IMHO to use conda, but that would break your requirement.

You can ask your question on https://groups.google.com/g/pandoc-discuss. I wish you the best of luck!

Cheers,

Sébastien
