### ISSUE TITLE
Can't install pandoc on windows

### ISSUE THREAD

**Issue by AlanCristhian** [boisgera/pandoc#6]
Here is the output error.

    C:\Users\usuario>python -m pip install pandoc
    Collecting pandoc==1.0.0a16
      Using cached pandoc-1.0.0a16.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "C:\Users\usuario\AppData\Local\Temp\pip-build-a7ar58bp\pandoc\setup.py", line 49, in <module>
            import about
          File "C:\Users\usuario\AppData\Local\Temp\pip-build-a7ar58bp\pandoc\.lib\about\__init__.py", line 15, in <module>
            from .about import *
        TypeError: 'dict_keys' object does not support indexing

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\usuario\AppData\Local\Temp\pip-build-yj8tbdle\pandoc\

The error info isn't very informative, maybe you can guess what is wrong.

Regards!

**Comment by boisgera** [comment]
Are you using Python 3? (this is not supported so far).

**Comment by boisgera** [comment]
Hi Alan, 

I have updated the README and the project metadata to make it clear that Python 3 is not supported at the moment.
 
However, AFAICT, pip for python 3 does not care and tries to install the package anyway.
If you know how to make it fail with a clear "Python 3 not supported" error, please let me know.

**Comment by mjalas** [comment]
Is there any specific reason for not supporting Python 3?

**Comment by boisgera** [comment]
@mjalas, 

Not really, at least I don't expect any technical show-stopper for the port. 
I don't really use Python 3 myself, that's all (but I understand the need).

There are a still a couple of things that I'd like to add before the 1.0.0 release 
(the test suite, a minimal documentation, support for pandoc 1.17, etc.).
I'll have a look at the effort needed to port to Python 3;
If this is straightforward, I'll add it to this shortlist, 
otherwise it will be a goal for another release.

**Comment by mjalas** [comment]
@boisgera ,

Alright, that's good news. I was hoping it only depended on you not using Python 3, which I can understand. Let me know if you need any help.

**Comment by boisgera** [comment]
OK, the basic port to Python 3 is done -- the same test suite passes for Python 2 and 3.
Let me run if you run into issues.

**Comment by AlanCristhian** [comment]
I don't found any isue with the new version. Thanks for port this to Python 3 :).
